@Library('pipeline-library') _

pipeline {
    agent any
    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO_CLIENT = 'pentera-client'
        AWS_ACCOUNT_ID = '390403894730'
        URL_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }
    parameters {
        string(name: 'RELEASE_VERSION_CLIENT', defaultValue: 'latest', description: 'Release version for Client Docker image')
    }

    stages {
        stage('Login to ECR') {
            steps {
                script {
                    dockerCommands.loginToECR(AWS_REGION, URL_REGISTRY)
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerCommands.buildDockerImage(ECR_REPO_CLIENT, params.RELEASE_VERSION_CLIENT, './web-app/client')
                }
            }
        }

        stage('Security Scan: Docker Image') {
            steps {
                script {
                    securityScans.scanDockerImage("${URL_REGISTRY}/${ECR_REPO_CLIENT}:${params.RELEASE_VERSION_CLIENT}")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    dockerCommands.tagAndPushDockerImage(ECR_REPO_CLIENT, params.RELEASE_VERSION_CLIENT, URL_REGISTRY)
                }
            }
        }
    }
}
