
- name: Update APT package index
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - curl
      - unzip
    state: present

- name: Download AWS CLI bundle
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"

- name: Unzip AWS CLI bundle
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Install AWS CLI
  command: "/tmp/aws/install --update"

- name: Verify AWS CLI installation
  command: "aws --version"
  register: aws_cli_version

- name: Display AWS CLI version
  debug:
    msg: "{{ aws_cli_version.stdout }}"
