services:
  server:
    image: public.ecr.aws/f4b7q1c5/server-pentera:latest
    ports:
      - "5000:5000" # Exposing port 5000 for external access
    networks:
      - app-network
    container_name: flask-server

  client:
    image: public.ecr.aws/f4b7q1c5/client-pentera:latest
    depends_on:
      - server
    ports:
      - "5001:5001"
    networks:
      - app-network
    container_name: flask-client
networks:
  app-network:
    driver: bridge
