services:
  server:
    image: public.ecr.aws/f4b7q1c5/server-pentera:latest
    ports:
      - "5000:5000" 
    networks:
      - app-network
    container_name: flask-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]  # Assuming there's a /health endpoint
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  client:
    image: public.ecr.aws/f4b7q1c5/client-pentera:latest
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "5001:5001"
    networks:
      - app-network
    container_name: flask-client
networks:
  app-network:
    driver: bridge
