services:
  server:
    image:
#    build:
#      context: ./server
#      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"  # Exposing port 5000 for external access
    volumes:
      - ./server:/app
    networks:
      - app-network
    container_name: flask-server

  client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile-client
    image:
    volumes:
      - ./client:/app
    depends_on:
      - server
    ports:
      - "5001:5001"
    networks:
      - app-network
    container_name: flask-client

networks:
  app-network:
    driver: bridge
