pipeline {
    agent any
    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO_SERVER = 'pentera-server'
        ECR_REPO_CLIENT = 'pentera-client'
        AWS_ACCOUNT_ID = '390403894730'
        URL_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }
    parameters {
        string(name: 'RELEASE_VERSION_SERVER', defaultValue: 'latest', description: 'Release version for Server Docker image')
        string(name: 'RELEASE_VERSION_CLIENT', defaultValue: 'latest', description: 'Release version for Client Docker image')

    }

    stages{
        stage('Security Scan: Dependencies') {
            steps {
                script {
                    sh """
                    . venv/bin/activate
                    pip3 install safety
                    safety check -r ./web-app/requirements.txt
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script{
                    sh """
                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${URL_REGISTRY}
                    docker build -t ${ECR_REPO_SERVER}:${params.RELEASE_VERSION_SERVER} ./web-app/server
                    docker build -t ${ECR_REPO_CLIENT}:${params.RELEASE_VERSION_CLIENT} ./web-app/client
                    """
                }
            }
        }

        stage('Security Scan: Docker Image') {
            steps {
                script {
                    sh """
                    trivy image ${ECR_REPO_SERVER}
                    trivy image ${ECR_REPO_CLIENT}
                    """
                }
            }
        
        
        stage('Push Docker Image') {
            steps {
                script{
                    sh """
                    docker tag ${ECR_REPO_SERVER}:${params.RELEASE_VERSION_SERVER} ${URL_REGISTRY}/${ECR_REPO_SERVER}:${params.RELEASE_VERSION_SERVER}
                    docker push ${URL_REGISTRY}/${ECR_REPO_SERVER}:${params.RELEASE_VERSION_SERVER}

                    docker tag ${ECR_REPO_CLIENT}:${params.RELEASE_VERSION_CLIENT} ${URL_REGISTRY}/${ECR_REPO_CLIENT}:${params.RELEASE_VERSION_CLIENT}
                    docker push ${URL_REGISTRY}/${ECR_REPO_CLIENT}:${params.RELEASE_VERSION_CLIENT}
                    """
                }
                
            }
        }

    }
}
}