@Library('pipeline-library') _

pipeline {
    agent any
    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO_SERVER = 'server-pentera'
        URL_REGISTRY = "public.ecr.aws/f4b7q1c5"
    }
    parameters {
        string(name: 'RELEASE_VERSION_SERVER', defaultValue: 'latest', description: 'Release version for Server Docker image')
    }

    stages {
        stage('Check for Changes') {
            steps {
                script {
                    def changes = sh(script: "git diff --name-only HEAD~1 | grep '^web-app/server/' || true", returnStdout: true).trim()
                    if (changes) {
                        echo "Changes detected in web-app/server: \n${changes}"
                    } else {
                        echo "No changes in web-app/server. Skipping pipeline."
                        currentBuild.result = 'ABORTED'
                        error("No changes detected in web-app/server")
                    }
                }
            }
        }
        stage('Login to ECR') {
            steps {
                script {
                    try{
                    dockerCommands.loginToECR(AWS_REGION, URL_REGISTRY)
                    }catch(Exception e){
                        echo "ERROR: Failed to log in to ECR - ${e.message}"
                        error("Failed to log in to ECR")
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    try{
                    dockerCommands.buildDockerImage(ECR_REPO_SERVER, params.RELEASE_VERSION_SERVER, './web-app/server')
                                    } catch(Exception e){
                        echo "ERROR: Failed to build Docker image - ${e.message}"
                        error("Failed to build Docker image")
                    }
                }
            }
        }

        stage('Security Scan: Docker Image') {
            steps {
                script {
                    catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE'){
                    securityScans.scanDockerImage(ECR_REPO_SERVER)
                }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    try{
                    dockerCommands.tagAndPushDockerImage(ECR_REPO_SERVER, params.RELEASE_VERSION_SERVER, URL_REGISTRY)
                    } catch(Exception e){
                        echo "ERROR: Failed to push Docker image - ${e.message}"
                        error("Failed to push Docker image")
                    }
                }
            }
        }
        stage('Depoly'){
            steps{
                script{
                    sh """
                    yq -i '.services.server.image = "${URL_REGISTRY}/${ECR_REPO_SERVER}:${params.RELEASE_VERSION_SERVER}"' ./web-app/docker-compose.yml
                    git add ./web-app/docker-compose.yml
                    git commit -m "Update server image version"
                    git pull origin main
                    git push origin main
                    """
                }
            }
        }
    }
}
